-- HYTEK Budget — Migration 16: NEUTRALIZED 2026-06-21 (no-op)
-- =============================================================================
-- THIS MIGRATION IS INTENTIONALLY DISABLED. DO NOT RE-ENABLE OR RE-RUN IT.
-- =============================================================================
--
-- WHY THIS IS NOW A NO-OP
-- -----------------------
-- The original body of this file added a `job_type` column to the SHARED
-- public.jobs table with a CHECK constraint:
--
--     CHECK (job_type IN ('single_building', 'multi_unit'))
--
-- That domain represented BUILDING SHAPE (a single building vs a multi-unit
-- development) for this Budget app. But public.jobs lives on the SHARED
-- Supabase project (gqtikz / hytek-detailing) used by several sibling apps,
-- and `job_type` was later claimed by the PURCHASING app for an entirely
-- different meaning:
--
--     LIVE constraint on gqtikz:  job_type IN ('customer', 'internal')
--
-- Re-applying this migration would COLLIDE with that live purchasing
-- constraint — either failing outright or, worse, silently re-narrowing the
-- column to the old building-shape domain and breaking purchasing, dispatch's
-- "New Job", and install. This exact collision was a real production incident
-- (default/constraint mismatch broke dispatch New Job, fixed 2026-06-11).
--
-- CURRENT OWNERSHIP OF THESE CONCEPTS (do not re-create either of them here)
-- -------------------------------------------------------------------------
--   * job_type        — owned by PURCHASING. Domain: 'customer' | 'internal'.
--   * building shape   — now lives in its OWN column, `building_type`
--                        (nullable), NOT in job_type. Budget's TypeScript
--                        `Job` type reads `building_type` accordingly.
--
-- This app is also MOTHBALLED (next.config.ts redirects every route to
-- hytek-install), so it has no live need for either column.
--
-- WHAT THIS FILE DOES NOW
-- -----------------------
-- Nothing. There is deliberately no DDL below. It does NOT drop, rename, or
-- alter anything live — neutralizing this migration must never touch the
-- shared schema. If a runner executes this file it is a harmless no-op.
--
-- HISTORICAL NOTE
-- ---------------
-- The original additive migration (ADD COLUMN job_type + CHECK
-- 'single_building'/'multi_unit' + DEFAULT 'multi_unit') is preserved only in
-- this file's git history. It was authored to make the schema catch up with
-- optimistically-written TypeScript/UI (src/lib/types.ts and the now-removed
-- dashboard/_client.tsx + jobs/[id]/page.tsx). Those readers have since been
-- refactored away; the only remaining reference is the Budget `Job` type,
-- which now points at `building_type`.
--
-- No transaction, no statements — intentionally empty.
